services:
  web:
    build: .
    network_mode: "host"
    volumes:
      - ".:/app"
    working_dir: "/app"
    command:
      - /bin/sh
      - -c
      - |
        bun i
        bun dev
    ports:
      - "5173:5173"
      - "3000:3000"
